# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PermitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PermitDemo
  pod 'Permit', :path => '../../../Permit/Permit.podspec', :testspecs => ['Tests']
end
